DROP TABLE IF EXISTS appointments;

CREATE TABLE appointments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timeslot TEXT NOT NULL, -- Format: "YYYY-MM-DD HH:MM" Gregorian
    phone_number TEXT NOT NULL,
    booking_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    invoice_id TEXT, -- Custom invoice ID generated by the app for this payment attempt
    payment_trans_id TEXT -- Transaction ID from Aqa-ye Pardakht after successful payment
);

-- Ensures a timeslot can only be booked once by anyone
CREATE UNIQUE INDEX IF NOT EXISTS idx_timeslot_unique ON appointments (timeslot);
-- Index for fetching appointments by phone number
CREATE INDEX IF NOT EXISTS idx_phone_number ON appointments (phone_number);
CREATE INDEX IF NOT EXISTS idx_invoice_id ON appointments (invoice_id);
CREATE INDEX IF NOT EXISTS idx_payment_trans_id ON appointments (payment_trans_id);


-- New table for user device information
DROP TABLE IF EXISTS user_devices;
CREATE TABLE user_devices (
    phone_number TEXT PRIMARY KEY, -- Each phone number has one primary device association
    device_id TEXT NOT NULL UNIQUE, -- Unique ID stored in user's cookie
    user_agent TEXT,
    last_login_ip TEXT,
    last_activity_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_device_id ON user_devices (device_id);